// <auto-generated />
using System;
using EasyGold.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyGold.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250409133532_AggiornamentoDTO")]
    partial class AggiornamentoDTO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbAllegato", b =>
                {
                    b.Property<int>("All_IDAllegato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("All_IDAllegato"));

                    b.Property<int>("All_Dimensione")
                        .HasColumnType("int");

                    b.Property<string>("All_EntitaRiferimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_Estensione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_NomeFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("All_RecordId")
                        .HasColumnType("int");

                    b.HasKey("All_IDAllegato");

                    b.ToTable("Allegati");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbCliente", b =>
                {
                    b.Property<int>("Utw_IDClienteAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Utw_IDClienteAuto"));

                    b.Property<DateTime>("Utw_DataAttivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Utw_DataDisattivazione")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Utw_IdStatoCliente")
                        .HasColumnType("int");

                    b.Property<int>("Utw_NegoziAttivabili")
                        .HasColumnType("int");

                    b.Property<int>("Utw_NegoziVirtuali")
                        .HasColumnType("int");

                    b.Property<string>("Utw_NomeConnessione")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Utw_PercorsoImmagini")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Utw_PercorsoReports")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Utw_Postazioni")
                        .HasColumnType("int");

                    b.Property<string>("Utw_StringaConnessione")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Utw_UtentiAttivi")
                        .HasColumnType("int");

                    b.HasKey("Utw_IDClienteAuto");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbDatiCliente", b =>
                {
                    b.Property<int>("Dtc_IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dtc_IDCliente"));

                    b.Property<bool>("Dtc_Annullato")
                        .HasColumnType("bit");

                    b.Property<string>("Dtc_CAP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Dtc_CapitaleSociale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Dtc_Citta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dtc_CodiceFiscale")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Dtc_Gioielleria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Dtc_IDValuta")
                        .HasColumnType("int");

                    b.Property<string>("Dtc_Indirizzo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dtc_Nazione")
                        .HasColumnType("int");

                    b.Property<string>("Dtc_NumeroContratto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_PEC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_PartitaIVA")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Dtc_Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dtc_REA")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Dtc_RagSocialePrincipale")
                        .HasColumnType("bit");

                    b.Property<string>("Dtc_RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dtc_Ranking")
                        .HasColumnType("int");

                    b.Property<string>("Dtc_ReferenteCellulare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteCognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_StatoRegione")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Dtc_IDCliente");

                    b.ToTable("DatiClienti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloCliente", b =>
                {
                    b.Property<int>("Mdc_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mdc_IDAuto"));

                    b.Property<bool>("Mdc_BloccoModulo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Mdc_DataAttivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Mdc_DataDisattivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Mdc_DataOraBlocco")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mdc_IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("Mdc_IDModulo")
                        .HasColumnType("int");

                    b.Property<string>("Mdc_Nota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Mdc_IDAuto");

                    b.HasIndex("Mdc_IDCliente");

                    b.HasIndex("Mdc_IDModulo");

                    b.ToTable("ModuloClienti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloEasygold", b =>
                {
                    b.Property<int>("Mde_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mde_IDAuto"));

                    b.Property<string>("Mde_CodEcomm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mde_Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mde_DescrizioneEstesa")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Mde_IDAuto");

                    b.ToTable("ModuloEasygold");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloEasygoldLang", b =>
                {
                    b.Property<int>("Mdeid_ID")
                        .HasColumnType("int");

                    b.Property<string>("Mdeid_DescEstesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mdeid_Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mdeid_ISONum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mdeid_ISONum"));

                    b.HasKey("Mdeid_ID");

                    b.ToTable("ModuloEasygoldLang");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbNazioni", b =>
                {
                    b.Property<int>("Naz_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Naz_id"));

                    b.Property<string>("Naz_Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Naz_id");

                    b.ToTable("Nazioni");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbNegozi", b =>
                {
                    b.Property<int>("Neg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Neg_id"));

                    b.Property<bool?>("Neg_Bloccato")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Neg_DataAttivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Neg_DataDisattivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Neg_DataOraBlocco")
                        .HasColumnType("datetime2");

                    b.Property<int>("Neg_IDCliente")
                        .HasColumnType("int");

                    b.Property<string>("Neg_NomeNegozio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Neg_Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Neg_RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Neg_id");

                    b.ToTable("Negozi");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbRuolo", b =>
                {
                    b.Property<int>("Ur_IDRuolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ur_IDRuolo"));

                    b.Property<string>("Ur_Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ur_IDRuolo");

                    b.ToTable("Ruoli");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbStatoCliente", b =>
                {
                    b.Property<int>("Stc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stc_id"));

                    b.Property<string>("Stc_Colore")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Stc_Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Stc_id");

                    b.ToTable("StatiCliente");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbUtente", b =>
                {
                    b.Property<int>("Ute_IDUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ute_IDUtente"));

                    b.Property<bool>("Ute_Bloccato")
                        .HasColumnType("bit");

                    b.Property<string>("Ute_Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ute_IDRuolo")
                        .HasColumnType("int");

                    b.Property<string>("Ute_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ute_NomeUtente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ute_Nota")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ute_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ute_IDUtente");

                    b.HasIndex("Ute_IDRuolo");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbValute", b =>
                {
                    b.Property<int>("Val_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Val_id"));

                    b.Property<decimal>("Val_Cambio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Val_Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Val_NumeroDecimali")
                        .HasColumnType("int");

                    b.Property<string>("Val_Simbolo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Val_SimboloRegCassa")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Val_id");

                    b.ToTable("Valute");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloCliente", b =>
                {
                    b.HasOne("EasyGold.API.Models.Entities.DbCliente", "Cliente")
                        .WithMany("ModuliClienti")
                        .HasForeignKey("Mdc_IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyGold.API.Models.Entities.DbModuloEasygold", "Modulo")
                        .WithMany("ModuliClienti")
                        .HasForeignKey("Mdc_IDModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbUtente", b =>
                {
                    b.HasOne("EasyGold.API.Models.Entities.DbRuolo", "Ruolo")
                        .WithMany()
                        .HasForeignKey("Ute_IDRuolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruolo");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbCliente", b =>
                {
                    b.Navigation("ModuliClienti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloEasygold", b =>
                {
                    b.Navigation("ModuliClienti");
                });
#pragma warning restore 612, 618
        }
    }
}
