// <auto-generated />
using System;
using EasyGold.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyGold.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250820092252_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbAllegato", b =>
                {
                    b.Property<int>("All_IDAllegato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("All_IDAllegato"));

                    b.Property<int>("All_Dimensione")
                        .HasColumnType("int");

                    b.Property<string>("All_EntitaRiferimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_Estensione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_NomeFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("All_RecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("All_IDAllegato");

                    b.ToTable("Allegati");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbCliente", b =>
                {
                    b.Property<int>("Utw_IDClienteAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Utw_IDClienteAuto"));

                    b.Property<DateTime>("Utw_DataAttivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Utw_DataDisattivazione")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Utw_IdStatoCliente")
                        .HasColumnType("int");

                    b.Property<int>("Utw_NegoziAttivabili")
                        .HasColumnType("int");

                    b.Property<int>("Utw_NegoziVirtuali")
                        .HasColumnType("int");

                    b.Property<string>("Utw_NomeConnessione")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Utw_PercorsoImmagini")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Utw_PercorsoReports")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Utw_Postazioni")
                        .HasColumnType("int");

                    b.Property<string>("Utw_StringaConnessione")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Utw_UtentiAttivi")
                        .HasColumnType("int");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Utw_IDClienteAuto");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbDatiCliente", b =>
                {
                    b.Property<int>("Dtc_IDDatiCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dtc_IDDatiCliente"));

                    b.Property<bool>("Dtc_Annullato")
                        .HasColumnType("bit");

                    b.Property<string>("Dtc_CAP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("Dtc_CapitaleSociale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Dtc_Citta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dtc_CodiceFiscale")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Dtc_Gioielleria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dtc_IDCliente")
                        .HasColumnType("int");

                    b.Property<int?>("Dtc_IDValuta")
                        .HasColumnType("int");

                    b.Property<string>("Dtc_Indirizzo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dtc_Nazione")
                        .HasColumnType("int");

                    b.Property<string>("Dtc_NumeroContratto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_PEC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_PartitaIVA")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Dtc_Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dtc_REA")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Dtc_RagSocialePrincipale")
                        .HasColumnType("bit");

                    b.Property<string>("Dtc_RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Dtc_Ranking")
                        .HasColumnType("int");

                    b.Property<string>("Dtc_ReferenteCellulare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteCognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_ReferenteWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dtc_StatoRegione")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Dtc_IDDatiCliente");

                    b.ToTable("DatiClienti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloCliente", b =>
                {
                    b.Property<int>("Mdc_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mdc_IDAuto"));

                    b.Property<bool>("Mdc_BloccoModulo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Mdc_DataAttivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Mdc_DataDisattivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Mdc_DataOraBlocco")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mdc_IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("Mdc_IDModulo")
                        .HasColumnType("int");

                    b.Property<string>("Mdc_Nota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Mdc_IDAuto");

                    b.HasIndex("Mdc_IDCliente");

                    b.HasIndex("Mdc_IDModulo");

                    b.ToTable("ModuloClienti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloEasygold", b =>
                {
                    b.Property<int>("Mde_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mde_IDAuto"));

                    b.Property<string>("Mde_CodEcomm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mde_Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mde_DescrizioneEstesa")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Mde_IDAuto");

                    b.ToTable("ModuloEasygold");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloEasygoldLang", b =>
                {
                    b.Property<int>("Mdeid_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mdeid_IDAuto"));

                    b.Property<string>("Mdeid_DescEstesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mdeid_Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mdeid_ID")
                        .HasColumnType("int");

                    b.Property<int>("Mdeid_ISONum")
                        .HasColumnType("int");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Mdeid_IDAuto");

                    b.ToTable("ModuloEasygoldLang");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbNazioni", b =>
                {
                    b.Property<int>("Naz_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Naz_id"));

                    b.Property<string>("Naz_Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Naz_id");

                    b.ToTable("Nazioni");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbNegozi", b =>
                {
                    b.Property<int>("Neg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Neg_id"));

                    b.Property<bool?>("Neg_Bloccato")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Neg_DataAttivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Neg_DataDisattivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Neg_DataOraBlocco")
                        .HasColumnType("datetime2");

                    b.Property<int>("Neg_IDCliente")
                        .HasColumnType("int");

                    b.Property<string>("Neg_NomeNegozio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Neg_Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Neg_RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Neg_id");

                    b.ToTable("Negozi");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbRuolo", b =>
                {
                    b.Property<int>("Ur_IDRuolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ur_IDRuolo"));

                    b.Property<string>("Ur_Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Ur_IDRuolo");

                    b.ToTable("Ruoli");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbStatoCliente", b =>
                {
                    b.Property<int>("Stc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stc_id"));

                    b.Property<string>("Stc_Colore")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Stc_Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Stc_id");

                    b.ToTable("StatiCliente");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbUtente", b =>
                {
                    b.Property<int>("Ute_IDUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ute_IDUtente"));

                    b.Property<bool>("Ute_Bloccato")
                        .HasColumnType("bit");

                    b.Property<string>("Ute_Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ute_IDRuolo")
                        .HasColumnType("int");

                    b.Property<string>("Ute_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ute_NomeUtente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ute_Nota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ute_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Ute_IDUtente");

                    b.HasIndex("Ute_IDRuolo");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbValoriTabelle", b =>
                {
                    b.Property<int>("rowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rowId"));

                    b.Property<string>("lst_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lst_itemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("lst_oldId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("rowCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowDeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("rowId");

                    b.ToTable("tbco_ValoriTabelle");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbValute", b =>
                {
                    b.Property<int>("Val_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Val_id"));

                    b.Property<decimal>("Val_Cambio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Val_Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Val_NumeroDecimali")
                        .HasColumnType("int");

                    b.Property<string>("Val_Simbolo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Val_SimboloRegCassa")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("rowcreated_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Val_id");

                    b.ToTable("Valute");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Cliente.Entities.ACL.DbModuliStampe", b =>
                {
                    b.Property<int>("Mst_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mst_IDAuto"));

                    b.Property<bool>("Mst_Annullato")
                        .HasColumnType("bit");

                    b.Property<string>("Mst_Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mst_NomeModulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Mst_TipoModulo")
                        .HasColumnType("int");

                    b.HasKey("Mst_IDAuto");

                    b.ToTable("tbco_moduliStampe");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Cliente.Entities.DbAuditLog", b =>
                {
                    b.Property<int>("Log_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Log_Id"));

                    b.Property<DateTime>("Log_ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Log_ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_RecordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Log_Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCauOrdinamento", b =>
                {
                    b.Property<int>("Cao_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cao_IDAuto"));

                    b.Property<int>("Cao_ID")
                        .HasColumnType("int");

                    b.Property<int>("Cao_Ordinamento")
                        .HasColumnType("int");

                    b.Property<int?>("DbCausaliComuneCac_IDAuto")
                        .HasColumnType("int");

                    b.HasKey("Cao_IDAuto");

                    b.HasIndex("Cao_ID");

                    b.HasIndex("DbCausaliComuneCac_IDAuto");

                    b.ToTable("tbco_cauOrdinamento");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCauProgressivi", b =>
                {
                    b.Property<int>("Cpr_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cpr_IDAuto"));

                    b.Property<bool>("Cpr_Annullato")
                        .HasColumnType("bit");

                    b.Property<int>("Cpr_CalcDisponibilita")
                        .HasColumnType("int");

                    b.Property<int>("Cpr_CalcGiacenza")
                        .HasColumnType("int");

                    b.Property<string>("Cpr_Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Cpr_IDAuto");

                    b.ToTable("tbco_cauProgressivi");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCauProgressiviLang", b =>
                {
                    b.Property<int>("Prcid_ISONum")
                        .HasColumnType("int");

                    b.Property<int>("Prcid_ID")
                        .HasColumnType("int");

                    b.Property<string>("Prcid_Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Prcid_ISONum", "Prcid_ID");

                    b.HasIndex("Prcid_ID");

                    b.ToTable("tbco_cauProgressivi_lang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCausaliComune", b =>
                {
                    b.Property<int>("Cac_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cac_IDAuto"));

                    b.Property<bool>("Cac_Annulla")
                        .HasColumnType("bit");

                    b.Property<string>("Cac_Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cac_IDDoveUso")
                        .HasColumnType("int");

                    b.Property<int>("Cac_IDProgressivo")
                        .HasColumnType("int");

                    b.Property<int>("Cac_IDTipoAnagrafica")
                        .HasColumnType("int");

                    b.Property<int>("Cac_IDTipoIVA")
                        .HasColumnType("int");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Cac_IDAuto");

                    b.ToTable("tbco_causali");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCausaliComuneLang", b =>
                {
                    b.Property<int>("Cac_ISONum")
                        .HasColumnType("int");

                    b.Property<int>("Cac_ID")
                        .HasColumnType("int");

                    b.Property<string>("Cac_Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cac_IDAuto")
                        .HasColumnType("int");

                    b.HasKey("Cac_ISONum", "Cac_ID");

                    b.HasIndex("Cac_ID");

                    b.ToTable("tbco_causali_lang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbDocumentiFunzione", b =>
                {
                    b.Property<int>("Dof_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dof_IDAuto"));

                    b.Property<bool>("Dof_Annulla")
                        .HasColumnType("bit");

                    b.Property<string>("Dof_Documento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dof_Funzione")
                        .HasColumnType("int");

                    b.Property<int>("Dof_ISONum")
                        .HasColumnType("int");

                    b.Property<int>("Dof_Sequenza")
                        .HasColumnType("int");

                    b.Property<int>("Dof_TipoDoc")
                        .HasColumnType("int");

                    b.HasKey("Dof_IDAuto");

                    b.ToTable("tbco_documentiFunzione");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbFunzioni", b =>
                {
                    b.Property<int>("Abl_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Abl_IDAuto"));

                    b.Property<bool?>("Abl_Annullato")
                        .HasColumnType("bit");

                    b.Property<string>("Abl_DescFunzione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Abl_DescFunzioneEstesa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Abl_IDPadre")
                        .HasColumnType("int");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Abl_IDAuto");

                    b.ToTable("tbco_funzioni");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbFunzioniLang", b =>
                {
                    b.Property<int>("Ablid_ID")
                        .HasColumnType("int");

                    b.Property<int>("Ablid_ISONum")
                        .HasColumnType("int");

                    b.Property<string>("Ablid_DescFunzione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ablid_descFunzioneEstesa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Ablid_ID", "Ablid_ISONum");

                    b.ToTable("tbco_funzioni_lang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbIdiomiEasyGold", b =>
                {
                    b.Property<int>("Idm_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idm_IDAuto"));

                    b.Property<int>("Idm_ISONum")
                        .HasColumnType("int");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Idm_IDAuto");

                    b.ToTable("tbco_idiomiEasygold");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbNazioniMondo", b =>
                {
                    b.Property<int>("Nzm_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nzm_IDAuto"));

                    b.Property<string>("Nzm_CapitaleAmm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nzm_CapitaleFatto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nzm_CapitaleIdioma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nzm_CapitaleIure")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nzm_ISOAlfa2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nzm_ISOAlfa3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("Nzm_ISONum")
                        .HasColumnType("int");

                    b.Property<string>("Nzm_Nazione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nzm_PrefTelefonico")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Nzm_IDAuto");

                    b.ToTable("tbco_nazioniMondo");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbNazioniMondoLang", b =>
                {
                    b.Property<int>("Nzmid_ID")
                        .HasColumnType("int");

                    b.Property<int>("Nzmid_ISONum")
                        .HasColumnType("int");

                    b.Property<string>("Nzmid_CapitaleAmm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nzmid_CapitaleFatto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nzmid_CapitaleIure")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nzmid_Nazione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Nzmid_ID", "Nzmid_ISONum");

                    b.ToTable("tbco_nazioniMondo_lang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbSessioniEasyGold", b =>
                {
                    b.Property<int>("Sse_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sse_IDAuto"));

                    b.Property<DateTime?>("Sse_DataLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Sse_DataLogout")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Sse_DataLogoutForzato")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sse_IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("Sse_IDUtente")
                        .HasColumnType("int");

                    b.Property<bool>("Sse_SesScaduta")
                        .HasColumnType("bit");

                    b.Property<bool?>("Sse_sesForzata")
                        .HasColumnType("bit");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Sse_IDAuto");

                    b.ToTable("tbco_SessioniEasyGold");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbTipoPermesso", b =>
                {
                    b.Property<int>("Tpa_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tpa_IDAuto"));

                    b.Property<int?>("Tpa_LivelloPermesso")
                        .HasColumnType("int");

                    b.Property<string>("Tpa_TipoPermesso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Tpa_IDAuto");

                    b.ToTable("tbco_tipoPermesso");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbTipoPermessoLang", b =>
                {
                    b.Property<int>("Tpaid_ISONum")
                        .HasColumnType("int");

                    b.Property<int>("Tpaid_ID")
                        .HasColumnType("int");

                    b.Property<string>("Tpaid_TipoAbilitazione")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Tpaid_ISONum", "Tpaid_ID");

                    b.ToTable("tbco_tipoPermesso_lang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbTipoTagProdotti", b =>
                {
                    b.Property<int>("Tpt_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tpt_IDAuto"));

                    b.Property<string>("Tpt_Descrizione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Tpt_NumGiorni")
                        .HasColumnType("int");

                    b.Property<int>("Tpt_TipoTag")
                        .HasColumnType("int");

                    b.HasKey("Tpt_IDAuto");

                    b.ToTable("tbco_tipoTagProdotti");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbISONazioni", b =>
                {
                    b.Property<int>("Ntn_ISO1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ntn_ISO1"));

                    b.Property<int>("Ntn_Appartiene")
                        .HasColumnType("int");

                    b.Property<string>("Ntn_Capitale")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ntn_CapitaleAmm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ntn_CapitaleDeFacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ntn_CapitaleIdioma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ntn_Continente")
                        .HasColumnType("int");

                    b.Property<int>("Ntn_ContinenteLegale")
                        .HasColumnType("int");

                    b.Property<string>("Ntn_DescStatoRegione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ntn_Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ntn_IDValuta")
                        .HasColumnType("int");

                    b.Property<string>("Ntn_ISO1A2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Ntn_ISO1A3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("Ntn_Indirizzi")
                        .HasColumnType("bit");

                    b.Property<bool>("Ntn_Localita")
                        .HasColumnType("bit");

                    b.Property<int>("Ntn_LungSiglaProv")
                        .HasColumnType("int");

                    b.Property<int>("Ntn_LunghezzaCAP")
                        .HasColumnType("int");

                    b.Property<int>("Ntn_LunghezzaCF")
                        .HasColumnType("int");

                    b.Property<int>("Ntn_LunghezzaPI")
                        .HasColumnType("int");

                    b.Property<string>("Ntn_NomeCF")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ntn_NomePI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ntn_PrefTelef")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Ntn_ProvSiNo")
                        .HasColumnType("bit");

                    b.Property<bool>("Ntn_Province")
                        .HasColumnType("bit");

                    b.Property<bool>("Ntn_StatoRegione")
                        .HasColumnType("bit");

                    b.Property<int>("Ntn_TipoCF")
                        .HasColumnType("int");

                    b.Property<int>("Ntn_TipoPI")
                        .HasColumnType("int");

                    b.HasKey("Ntn_ISO1");

                    b.ToTable("tbco_ISONazioni");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIdISONazioni", b =>
                {
                    b.Property<int>("Ntnid_ISONum")
                        .HasColumnType("int");

                    b.Property<int>("Ntnid_ID")
                        .HasColumnType("int");

                    b.Property<string>("Ntn_CapitaleAmm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ntn_CapitaleDeFacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ntnid_Capitale")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ntnid_Nazione")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Ntnid_ISONum", "Ntnid_ID");

                    b.HasIndex("Ntnid_ID");

                    b.ToTable("tbco_id_ISONazioni");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIdStatoRegioni", b =>
                {
                    b.Property<int>("Strid_ISONum")
                        .HasColumnType("int");

                    b.Property<int>("Strid_ID")
                        .HasColumnType("int");

                    b.Property<string>("Strid_Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Strid_ISONum", "Strid_ID");

                    b.HasIndex("Strid_ID");

                    b.ToTable("tbco_id_statoRegioni");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIndirizzi", b =>
                {
                    b.Property<int>("Str_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Str_IDAuto"));

                    b.Property<string>("Str_CAP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Str_CodLocalita")
                        .HasColumnType("int");

                    b.Property<string>("Str_Descrizione")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Str_ISO1")
                        .HasColumnType("int");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Str_IDAuto");

                    b.ToTable("tbco_indirizzi");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIndirizziLang", b =>
                {
                    b.Property<int>("Strid_ISONum")
                        .HasColumnType("int");

                    b.Property<int>("Strid_ID")
                        .HasColumnType("int");

                    b.Property<string>("Strid_Descrizione")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Strid_ISONum", "Strid_ID");

                    b.HasIndex("Strid_ID");

                    b.ToTable("tbco_indirizzi_lang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbLocalita", b =>
                {
                    b.Property<int>("Str_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Str_IDAuto"));

                    b.Property<string>("Str_CAP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Str_CodProvincia")
                        .HasColumnType("int");

                    b.Property<int>("Str_CodStatoRegione")
                        .HasColumnType("int");

                    b.Property<string>("Str_Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Str_ISO1")
                        .HasColumnType("int");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Str_IDAuto");

                    b.ToTable("tbco_localita");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbLocalitaLang", b =>
                {
                    b.Property<int>("Strid_ISONum")
                        .HasColumnType("int");

                    b.Property<int>("Strid_ID")
                        .HasColumnType("int");

                    b.Property<string>("Strid_Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("rowcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowdeleted_at")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("rowupdated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("Strid_ISONum", "Strid_ID");

                    b.HasIndex("Strid_ID");

                    b.ToTable("tbco_localita_lang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbProvince", b =>
                {
                    b.Property<int>("Str_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Str_IDAuto"));

                    b.Property<int>("Str_CodStatoRegione")
                        .HasColumnType("int");

                    b.Property<string>("Str_Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Str_ISO1")
                        .HasColumnType("int");

                    b.Property<string>("Str_SiglaTargaAuto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Str_IDAuto");

                    b.ToTable("tbco_province");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbProvinceLang", b =>
                {
                    b.Property<int>("Strid_ISONum")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Strid_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("Strid_Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Strid_ISONum", "Strid_ID");

                    b.HasIndex("Strid_ID");

                    b.ToTable("tbco_province_lang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbStatoRegioni", b =>
                {
                    b.Property<int>("Str_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Str_IDAuto"));

                    b.Property<int>("Str_CodCapoluogo")
                        .HasColumnType("int");

                    b.Property<string>("Str_Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Str_ISO1")
                        .HasColumnType("int");

                    b.HasKey("Str_IDAuto");

                    b.ToTable("tbco_statoRegioni");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloCliente", b =>
                {
                    b.HasOne("EasyGold.API.Models.Entities.DbCliente", "Cliente")
                        .WithMany("ModuliClienti")
                        .HasForeignKey("Mdc_IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyGold.API.Models.Entities.DbModuloEasygold", "Modulo")
                        .WithMany("ModuliClienti")
                        .HasForeignKey("Mdc_IDModulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbUtente", b =>
                {
                    b.HasOne("EasyGold.API.Models.Entities.DbRuolo", "Ruolo")
                        .WithMany()
                        .HasForeignKey("Ute_IDRuolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruolo");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCauOrdinamento", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.Entities.ACL.DbCausaliComune", "CausaleComune")
                        .WithMany()
                        .HasForeignKey("Cao_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyGold.Web2.Models.Comune.Entities.ACL.DbCausaliComune", null)
                        .WithMany("Ordinamenti")
                        .HasForeignKey("DbCausaliComuneCac_IDAuto");

                    b.Navigation("CausaleComune");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCauProgressiviLang", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.Entities.ACL.DbCauProgressivi", "CauProgressivo")
                        .WithMany("CauProgressiviLang")
                        .HasForeignKey("Prcid_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauProgressivo");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCausaliComuneLang", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.Entities.ACL.DbCausaliComune", "CausaliComune")
                        .WithMany("CausaliComuneLang")
                        .HasForeignKey("Cac_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CausaliComune");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbFunzioniLang", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.Entities.ACL.DbFunzioni", "Funzione")
                        .WithMany("FunzioniLang")
                        .HasForeignKey("Ablid_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funzione");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbNazioniMondoLang", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.Entities.ACL.DbNazioniMondo", "NazioneMondo")
                        .WithMany("NazioniMondoLang")
                        .HasForeignKey("Nzmid_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NazioneMondo");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIdISONazioni", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbISONazioni", "ISONazione")
                        .WithMany("IdISONazioniLang")
                        .HasForeignKey("Ntnid_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ISONazione");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIdStatoRegioni", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbStatoRegioni", "StatoRegione")
                        .WithMany("IdStatoRegioni")
                        .HasForeignKey("Strid_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatoRegione");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIndirizziLang", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIndirizzi", "Indirizzo")
                        .WithMany("IndirizziLang")
                        .HasForeignKey("Strid_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indirizzo");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbLocalitaLang", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbLocalita", "Localita")
                        .WithMany("LocalitaLang")
                        .HasForeignKey("Strid_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localita");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbProvinceLang", b =>
                {
                    b.HasOne("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbProvince", "Province")
                        .WithMany("ProvinceLang")
                        .HasForeignKey("Strid_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbCliente", b =>
                {
                    b.Navigation("ModuliClienti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbModuloEasygold", b =>
                {
                    b.Navigation("ModuliClienti");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCauProgressivi", b =>
                {
                    b.Navigation("CauProgressiviLang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbCausaliComune", b =>
                {
                    b.Navigation("CausaliComuneLang");

                    b.Navigation("Ordinamenti");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbFunzioni", b =>
                {
                    b.Navigation("FunzioniLang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.Entities.ACL.DbNazioniMondo", b =>
                {
                    b.Navigation("NazioniMondoLang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbISONazioni", b =>
                {
                    b.Navigation("IdISONazioniLang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbIndirizzi", b =>
                {
                    b.Navigation("IndirizziLang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbLocalita", b =>
                {
                    b.Navigation("LocalitaLang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbProvince", b =>
                {
                    b.Navigation("ProvinceLang");
                });

            modelBuilder.Entity("EasyGold.Web2.Models.Comune.GEO.Entities.ACL.DbStatoRegioni", b =>
                {
                    b.Navigation("IdStatoRegioni");
                });
#pragma warning restore 612, 618
        }
    }
}
