// <auto-generated />
using EasyGold.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyGold.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbCliente", b =>
            {
                b.Property<int>("Utw_IDClienteAuto")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Utw_IDClienteAuto"));

                b.Property<string>("Utw_NomeConnessione")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Utw_StringaConnessione")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("Utw_DataAttivazione")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("Utw_DataDisattivazione")
                    .HasColumnType("datetime2");

                b.Property<int>("Utw_NegoziAttivabili")
                    .HasColumnType("int");

                b.Property<int>("Utw_NegoziVirtuali")
                    .HasColumnType("int");

                b.Property<int>("Utw_UtentiAttivi")
                    .HasColumnType("int");

                b.Property<string>("Utw_PercorsoReports")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Utw_PercorsoImmagini")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("Utw_Blocco")
                    .HasColumnType("bit");

                b.HasKey("Utw_IDClienteAuto");

                b.ToTable("DbCliente");
            });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbUtente", b =>
            {
                b.Property<int>("Ute_IDUtente")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ute_IDUtente"));

                b.Property<string>("Ute_NomeUtente")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Ute_TipoAbilitazione")
                    .HasColumnType("int");

                b.Property<bool>("Ute_Bloccato")
                    .HasColumnType("bit");

                b.Property<string>("Ute_Nota")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Ute_IDUtente");

                b.ToTable("DbUtente");
            });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbDatiCliente", b =>
            {
                b.Property<int>("Dtc_IDCliente")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Dtc_IDCliente"));

                b.Property<string>("Dtc_Gioielleria")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_RagioneSociale")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_Indirizzo")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_CAP")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_Localita")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_Provincia")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_StatoRegione")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_Nazione")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_PartitaIVA")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_CodiceFiscale")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Dtc_REA")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Dtc_CapitaleSociale")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Dtc_IDCliente");

                b.ToTable("DbDatiCliente");
            });
        }
    }
}
