// <auto-generated />
using System;
using EasyGold.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyGold.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250507133230_AggiornamentoDTO")]
    partial class AggiornamentoDTO
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyGold.API.Models.Entities.Allegati.DbAllegato", b =>
                {
                    b.Property<int>("All_IDAllegato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("All_IDAllegato"));

                    b.Property<int>("All_Dimensione")
                        .HasColumnType("int");

                    b.Property<string>("All_EntitaRiferimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_Estensione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_NomeFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("All_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("All_RecordId")
                        .HasColumnType("int");

                    b.HasKey("All_IDAllegato");

                    b.ToTable("Allegati");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Config.DbConfig", b =>
                {
                    b.Property<int>("Sys_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sys_IDAuto"));

                    b.Property<int?>("Sys_IDNazione")
                        .HasColumnType("int");

                    b.Property<int?>("Sys_Lunghezza")
                        .HasColumnType("int");

                    b.Property<string>("Sys_NomeCampo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sys_Sezione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sys_TipoCampo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sys_Valore")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sys_IDAuto");

                    b.ToTable("syscl_config");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Config.DbConfigLang", b =>
                {
                    b.Property<int>("SysLng_ISONum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysLng_ISONum"));

                    b.Property<int>("SysLng_ID")
                        .HasColumnType("int");

                    b.Property<string>("SysLng_NomeCampo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SysLng_ISONum");

                    b.ToTable("syscl_configLang");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbAuditLog", b =>
                {
                    b.Property<int>("Log_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Log_Id"));

                    b.Property<DateTime>("Log_ChangeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Log_ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_RecordId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Log_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Log_Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.DbNegozi", b =>
                {
                    b.Property<int>("Neg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Neg_id"));

                    b.Property<bool?>("Neg_Bloccato")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Neg_DataAttivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Neg_DataDisattivazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Neg_DataOraBlocco")
                        .HasColumnType("datetime2");

                    b.Property<int>("Neg_IDCliente")
                        .HasColumnType("int");

                    b.Property<string>("Neg_NomeNegozio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Neg_Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Neg_RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Neg_id");

                    b.ToTable("Negozi");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Moduli.DbModuloEasygold", b =>
                {
                    b.Property<int>("Mde_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mde_IDAuto"));

                    b.Property<string>("Mde_CodEcomm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mde_Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mde_DescrizioneEstesa")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Mde_IDAuto");

                    b.ToTable("ModuloEasygold");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Moduli.DbModuloEasygoldLang", b =>
                {
                    b.Property<int>("Mdeid_IDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mdeid_IDAuto"));

                    b.Property<string>("Mdeid_DescEstesa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mdeid_Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mdeid_ID")
                        .HasColumnType("int");

                    b.Property<int>("Mdeid_ISONum")
                        .HasColumnType("int");

                    b.HasKey("Mdeid_IDAuto");

                    b.ToTable("ModuloEasygoldLang");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Nazioni.DbNazioni", b =>
                {
                    b.Property<int>("Ntn_ISO1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ntn_ISO1"));

                    b.Property<string>("Ntn_Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Ntn_ISO1");

                    b.ToTable("tbco_ISONazioni");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.NumeriRegIVA.DbNumeriRegIVA", b =>
                {
                    b.Property<int>("RowIDAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowIDAuto"));

                    b.Property<int>("Nri_Anno")
                        .HasColumnType("int");

                    b.Property<int>("Nri_NumFattura")
                        .HasColumnType("int");

                    b.Property<int>("RowIDRegIVA")
                        .HasColumnType("int");

                    b.HasKey("RowIDAuto");

                    b.ToTable("NumeriRegIVA");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.RegIVA.DbRegistroIVA", b =>
                {
                    b.Property<int>("RowIdAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RowIdAuto"));

                    b.Property<bool>("Rgi_Annulla")
                        .HasColumnType("bit");

                    b.Property<string>("Rgi_Descrizione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rgi_Prefisso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Rgi_Suffisso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RowIdAuto");

                    b.ToTable("RegistriIVA");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Ruoli.DbRuolo", b =>
                {
                    b.Property<int>("Ur_IDRuolo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ur_IDRuolo"));

                    b.Property<string>("Ur_Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ur_IDRuolo");

                    b.ToTable("Ruoli");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Utenti.DbUtente", b =>
                {
                    b.Property<int>("Ute_IDUtente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ute_IDUtente"));

                    b.Property<bool>("Ute_Bloccato")
                        .HasColumnType("bit");

                    b.Property<string>("Ute_Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ute_IDRuolo")
                        .HasColumnType("int");

                    b.Property<string>("Ute_Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ute_NomeUtente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ute_Nota")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ute_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ute_IDUtente");

                    b.HasIndex("Ute_IDRuolo");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Valute.DbValute", b =>
                {
                    b.Property<int>("Val_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Val_id"));

                    b.Property<decimal>("Val_Cambio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Val_Descrizione")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Val_NumeroDecimali")
                        .HasColumnType("int");

                    b.Property<string>("Val_Simbolo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Val_SimboloRegCassa")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Val_id");

                    b.ToTable("Valute");
                });

            modelBuilder.Entity("EasyGold.API.Models.Entities.Utenti.DbUtente", b =>
                {
                    b.HasOne("EasyGold.API.Models.Entities.Ruoli.DbRuolo", "Ruolo")
                        .WithMany()
                        .HasForeignKey("Ute_IDRuolo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ruolo");
                });
#pragma warning restore 612, 618
        }
    }
}
